[package]
name = "spritesheet_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive", "string"] }
image = "0.25.2"
itertools = "0.13.0"
texture_packer = "0.29.0"
